name: 'Run SSH4Me'
on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SSH4Me Action
        uses: Jisan09/SSH4Me@main
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Configuring Ngrok Token ..
        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
      - name: Running Ngrok ..   
        run: ngrok http --domain=${{secrets.NGROK_DOMAIN}} 22
